server:
  port: 8070

spring:
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "rabbit"
    password: "rabbit"
    #username: "guest"
    #password: "guest"
  application:
    name: "configserver"
  profiles:
    active: "git"
    #active: native   # Used Only when search-location wity classpath and Filepath
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/Narendran3678/SpringBootMSConfig.git"
          default-label: main
          timeout: 5
          clone-on-start: true
        #native:
          #search-location: "classpath:/config"
          #search-location: "file:///Users/narendran.babu/Eclipse_Workspace/MyRepo/Practise/SpringBootMicroservices_V2/BankConfigServer/src/main/resources/config"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: "5C816A3B7A44A1825ACF9BB3BA37D"