#CREATE SCHEMA bankdb ;
USE BANKDB;
DROP TABLE CUSTOMERS;
DROP TABLE ACCOUNTS;
CREATE TABLE CUSTOMERS (
	CUSTOMERID BIGINT NOT NULL AUTO_INCREMENT,
    CUSTOMERNAME VARCHAR(100) NOT NULL DEFAULT '',
    EMAILID VARCHAR(100) NOT NULL DEFAULT '',
    MOBILENUMBER VARCHAR(100) NOT NULL DEFAULT '',
    ACTIVEFLAG TINYINT DEFAULT '1',
    CREATEDBY VARCHAR(100) DEFAULT '',
    CREATEDTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIEDBY VARCHAR(100) DEFAULT '',
    MODIFIEDTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (CUSTOMERID),
    UNIQUE KEY (EMAILID)
);

CREATE TABLE ACCOUNTS (
	CUSTOMERID BIGINT NOT NULL DEFAULT '0',
	ACCOUNTNUMBER VARCHAR(50) NOT NULL DEFAULT '',
	ACCOUNTTYPE VARCHAR(100) NOT NULL DEFAULT '',
    BRANCHADDRESS VARCHAR(100) NOT NULL DEFAULT '',
    CREATEDBY VARCHAR(100) DEFAULT '',
    CREATEDTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIEDBY VARCHAR(100) DEFAULT '',
    MODIFIEDTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (CUSTOMERID),
    UNIQUE KEY (ACCOUNTNUMBER),
    FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMERS(CUSTOMERID)
);
CREATE TABLE IF NOT EXISTS CARDS (
  CARD_ID INT NOT NULL AUTO_INCREMENT,
  MOBILE_NUMBER VARCHAR(15) NOT NULL,
  CARD_NUMBER VARCHAR(100) NOT NULL,
  CARD_TYPE VARCHAR(100) NOT NULL,
  TOTAL_LIMIT INT NOT NULL,
  AMOUNT_USED INT NOT NULL,
  AVAILABLE_AMOUNT INT NOT NULL,
  CREATED_AT DATE NOT NULL,
  CREATED_BY VARCHAR(20) NOT NULL,
  UPDATED_AT DATE DEFAULT NULL,
  UPDATED_BY VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (CARD_ID)
);
TRUNCATE CUSTOMERS;
SELECT * FROM CUSTOMERS;
SELECT * FROM ACCOUNTS;


DELETE FROM ACCOUNTS WHERE CUSTOMERID IN (SELECT CUSTOMERID FROM CUSTOMERS WHERE CUSTOMERNAME='Khadar');
DELETE FROM CUSTOMERS WHERE CUSTOMERNAME='Khadar';
