use devdb;
DROP TABLE EMPLOYEE_ROLE;
DROP TABLE EMPLOYEE;
DROP TABLE ROLE;

CREATE TABLE ROLE (
	ID BIGINT NOT NULL AUTO_INCREMENT,
    ROLE_ID BIGINT NOT NULL,
    ROLENAME VARCHAR(100) NOT NULL,
    PRIMARY KEY(ID),
    UNIQUE(ROLE_ID,ROLENAME)
);
CREATE TABLE EMPLOYEE (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  FIRSTNAME VARCHAR(255) DEFAULT NULL,
  LASTNAME VARCHAR(255) DEFAULT NULL,
  EMAILID VARCHAR(255) DEFAULT NULL,
  PHONENUMBER VARCHAR(255) DEFAULT NULL,
  SALARY DOUBLE DEFAULT NULL,
  CREATETIME DATETIME(6) DEFAULT NULL,
  LASTMODIFIED DATETIME(6) DEFAULT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY(EMAILID)
);

CREATE TABLE EMPLOYEE_ROLE (
ROLE_ID BIGINT,
EMPLOYEE_ID BIGINT,
UNIQUE KEY(ROLE_ID,EMPLOYEE_ID),
FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID),
FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(ID)
);

INSERT INTO EMPLOYEE (salary, createtime, lastmodified, emailid, firstname, lastname, phonenumber)
VALUES ('30000',sysdate(),  sysdate(), 'divya@gmail.com','Divya', 'Naren', '8200212110');

INSERT INTO EMPLOYEE (salary, createtime, lastmodified, emailid, firstname, lastname, phonenumber)
VALUES ('50000',sysdate(),  sysdate(), 'naren@gmail.com','Narendran', 'Naren', '7092802533');

INSERT INTO EMPLOYEE (salary, createtime, lastmodified, emailid, firstname, lastname, phonenumber)
VALUES ('100000',sysdate(),  sysdate(), 'sam@gmail.com','Sam', 'Sam', '8912428787');

INSERT INTO EMPLOYEE (salary, createtime, lastmodified, emailid, firstname, lastname, phonenumber)
VALUES ('100000',sysdate(),  sysdate(), 'john@gmail.com','John', 'John', '8912428787');

INSERT INTO ROLE (ROLE_ID,ROLENAME) VALUES (1,'Admin');
INSERT INTO ROLE (ROLE_ID,ROLENAME) VALUES (2,'Manager');
INSERT INTO ROLE (ROLE_ID,ROLENAME) VALUES (3,'Employee');

INSERT INTO EMPLOYEE_ROLE (ROLE_ID,EMPLOYEE_ID) VALUE(1,1);
INSERT INTO EMPLOYEE_ROLE (ROLE_ID,EMPLOYEE_ID) VALUE(2,2);
INSERT INTO EMPLOYEE_ROLE (ROLE_ID,EMPLOYEE_ID) VALUE(3,3);
INSERT INTO EMPLOYEE_ROLE (ROLE_ID,EMPLOYEE_ID) VALUE(1,4);

SELECT * FROM EMPLOYEE;
SELECT * FROM ROLE;
SELECT * FROM EMPLOYEE_ROLE;

commit;