drop table Book_Author;
drop table Book;
drop table Publisher;
drop table Author;

CREATE TABLE Author
(
    id number Generated by default on null as identity,
    name varchar(200) not null,
    primary key (id)
);

CREATE TABLE Publisher
(
    id number Generated by default on null as identity,
    name varchar(200) not null,
    primary key (id)
);
CREATE TABLE Book
(
    id number Generated by default on null as identity,
    title varchar(500) not null, 
    publication_year number,
    publisher_id number,
    book_genre_id number,
    amazon_rating number,
    kid_friendly_status number,
    created_date timestamp,
    FOREIGN KEY (publisher_id) REFERENCES Publisher(id),
    constraint book_unique_key UNIQUE(title, publication_year, publisher_id),
    primary key (id)
);

CREATE TABLE Book_Author 
(
    id number Generated by default on null as identity,
    book_id number not null,
    author_id number not null,
    FOREIGN KEY (book_id) REFERENCES Book(id),
    FOREIGN KEY (author_id) REFERENCES Author(id),
    constraint book_author_unique UNIQUE(book_id, author_id),
    primary key (id)
);

create table Multimedia
(
    id number Generated by default on null as identity,
    file_name varchar2(100),
    image_content blob,
    file_content clob,
    primary key(id)
);

INSERT INTO Author (name) VALUES ('Henry David Thoreau');
INSERT INTO Author (name) VALUES ('Ralph Waldo Emerson');
INSERT INTO Author (name) VALUES ('Lillian Eichler Watson');
INSERT INTO Author (name) VALUES ('Eric Freeman');
INSERT INTO Author (name) VALUES ('Bert Bates');
INSERT INTO Author (name) VALUES ('Kathy Sierra');
INSERT INTO Author (name) VALUES ('Elisabeth Robson');
INSERT INTO Author (name) VALUES ('Joshua Bloch');

INSERT INTO Publisher (name) VALUES ('Wilder Publications');
Insert into PUBLISHER (ID,NAME) values (2,'Kranthi Publications');

insert into book (title,publication_year,publisher_id,book_genre_id,amazon_rating,kid_friendly_status,created_date) 
values('Java Programming',1997,1,100,4,1,systimestamp);

insert into book (title,publication_year,publisher_id,book_genre_id,amazon_rating,kid_friendly_status,created_date) 
values('C# Programming',1994,2,101,4.5,1,systimestamp);

insert into book (title,publication_year,publisher_id,book_genre_id,amazon_rating,kid_friendly_status,created_date) 
values('Bio Crypto',2001,1,102,3.5,1,systimestamp);

Insert into Book_Author (ID,book_id,author_id) values (1,2,1);
Insert into Book_Author (ID,book_id,author_id) values (2,3,2);
Insert into Book_Author (ID,book_id,author_id) values (3,4,3);


SELECT S.* FROM Book_Author s;
SELECT S.* FROM Book s;
SELECT S.* FROM Publisher s;
SELECT S.* FROM Author s;
commit;