use cardsdb;
CREATE TABLE IF NOT EXISTS CARDS (
  CARD_ID INT NOT NULL AUTO_INCREMENT,
  MOBILE_NUMBER VARCHAR(15) NOT NULL,
  CARD_NUMBER VARCHAR(100) NOT NULL,
  CARD_TYPE VARCHAR(100) NOT NULL,
  TOTAL_LIMIT INT NOT NULL,
  AMOUNT_USED INT NOT NULL,
  AVAILABLE_AMOUNT INT NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CREATED_BY VARCHAR(20) NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_BY VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (CARD_ID)
);