server:
  port: 8070

spring:
  application:
    name: "configserver"
  profiles:
    active: "git"
    #active: native   # Used Only when search-location wity classpath and Filepath
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/Narendran3678/SpringBootMSConfig.git"
          default-label: main
          timeout: 5
          clone-on-start: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics: # For Prometheus
    tags:
      application: ${spring.application.name}

encrypt:
  key: "5C816A3B7A44A1825ACF9BB3BA37D"