use loansdb;
CREATE TABLE IF NOT EXISTS LOANS (
  LOAN_ID INT NOT NULL AUTO_INCREMENT,
  MOBILE_NUMBER VARCHAR(15) NOT NULL,
  LOAN_NUMBER VARCHAR(100) NOT NULL,
  LOAN_TYPE VARCHAR(100) NOT NULL,
  TOTAL_LOAN INT NOT NULL,
  AMOUNT_PAID INT NOT NULL,
  OUTSTANDING_AMOUNT INT NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CREATED_BY VARCHAR(20) NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_BY VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (LOAN_ID)
);