use devdb;
set autocommit=0;

drop table movie;
drop table director;

CREATE TABLE DIRECTOR
(
	ID INT NOT NULL AUTO_INCREMENT,
    DIRECTOR_NAME VARCHAR(100) NOT NULL DEFAULT '',
    MOVIE_COUNT INT DEFAULT '0',
    PRIMARY KEY(ID)
);

CREATE TABLE MOVIE
(
	ID INT NOT NULL AUTO_INCREMENT,
    DIRECTOR_ID INT NOT NULL DEFAULT '0',
    MOVIE_NAME VARCHAR(100) NOT NULL DEFAULT '',
	PRIMARY KEY(ID),
    UNIQUE(DIRECTOR_ID,MOVIE_NAME),
    FOREIGN KEY (DIRECTOR_ID) REFERENCES DIRECTOR(ID)
);

INSERT INTO DIRECTOR (DIRECTOR_NAME,MOVIE_COUNT) VALUE('James Cameron',10);
INSERT INTO MOVIE (DIRECTOR_ID,MOVIE_NAME) VALUE((SELECT ID FROM DIRECTOR WHERE DIRECTOR_NAME='James Cameron'),'Titanic');
INSERT INTO MOVIE (DIRECTOR_ID,MOVIE_NAME) VALUE((SELECT ID FROM DIRECTOR WHERE DIRECTOR_NAME='James Cameron'),'Avatar');

select * from director;
select * from movie;

delete from director;
delete from movie;

commit;