use devdb;
set autocommit =1;

DROP TABLE INSTRUCTOR;
DROP TABLE INSTRUCTOR_DETAIL;
DROP TABLE COURSE;


CREATE TABLE INSTRUCTOR_DETAIL
(
	INSTRUCTOR_ID BIGINT NOT NULL AUTO_INCREMENT,
	EMAIL_ID VARCHAR(100) NOT NULL,
	PHONE_NUMBER VARCHAR(100) NOT NULL,
	CREATETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	MODIFYTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(INSTRUCTOR_ID)
);

CREATE TABLE COURSE 
(
	COURSE_ID BIGINT NOT NULL AUTO_INCREMENT,
    INSTRUCTOR_ID BIGINT NOT NULL,
    COURSE_NAME VARCHAR(100) NOT NULL DEFAULT '' UNIQUE,
	CREATETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	MODIFYTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(COURSE_ID),
    UNIQUE KEY(INSTRUCTOR_ID,COURSE_NAME)
);

CREATE TABLE INSTRUCTOR
(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100) NOT NULL DEFAULT '',
	CREATETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	MODIFYTIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(ID),
    FOREIGN KEY (ID) REFERENCES INSTRUCTOR_DETAIL(INSTRUCTOR_ID),
    FOREIGN KEY (ID) REFERENCES COURSE(INSTRUCTOR_ID)
);

    
INSERT INTO INSTRUCTOR_DETAIL (EMAIL_ID,PHONE_NUMBER) VALUE ('narendran3678@gmail.com','7092802533');
INSERT INTO COURSE (INSTRUCTOR_ID,COURSE_NAME) VALUE ((SELECT INSTRUCTOR_ID FROM INSTRUCTOR_DETAIL WHERE EMAIL_ID='narendran3678@gmail.com'),'Hibernate');
INSERT INTO INSTRUCTOR (id,name) VALUE ((SELECT INSTRUCTOR_ID FROM INSTRUCTOR_DETAIL WHERE EMAIL_ID='narendran3678@gmail.com'),'Narendran');

SELECT * FROM INSTRUCTOR;
SELECT * FROM INSTRUCTOR_DETAIL;
SELECT * FROM COURSE ;

delete from instructor;
delete from instructor_detail;
delete from COURSE;

commit;