USE accountsdb;

CREATE TABLE IF NOT EXISTS `CUSTOMERS` (
	`CUSTOMERID` BIGINT NOT NULL AUTO_INCREMENT,
    `CUSTOMERNAME` VARCHAR(100) NOT NULL DEFAULT '',
    `EMAILID` VARCHAR(100) NOT NULL DEFAULT '',
    `MOBILENUMBER` VARCHAR(100) NOT NULL DEFAULT '',
    `ACTIVEFLAG` TINYINT DEFAULT '1',
    `CREATEDBY` VARCHAR(100) DEFAULT '',
    `CREATEDTIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `MODIFIEDBY` VARCHAR(100) DEFAULT '',
    `MODIFIEDTIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`CUSTOMERID`),
    UNIQUE KEY (`EMAILID`)
);

CREATE TABLE IF NOT EXISTS `ACCOUNTS` (
	`CUSTOMERID` BIGINT NOT NULL DEFAULT '0',
	`ACCOUNTNUMBER` VARCHAR(50) NOT NULL DEFAULT '',
	`ACCOUNTTYPE` VARCHAR(100) NOT NULL DEFAULT '',
    `BRANCHADDRESS` VARCHAR(100) NOT NULL DEFAULT '',
    `CREATEDBY` VARCHAR(100) DEFAULT '',
    `CREATEDTIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `MODIFIEDBY` VARCHAR(100) DEFAULT '',
    `MODIFIEDTIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`CUSTOMERID`),
    UNIQUE KEY (`ACCOUNTNUMBER`),
    FOREIGN KEY (`CUSTOMERID`) REFERENCES `CUSTOMERS`(`CUSTOMERID`)
);