#Server Information
server:
  port: 8081
  servlet:
    context-path: /bank

#Database Properties
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bankdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

#OpenApi
springdoc:
  api-docs:
    path: /api-docs

customer:
  account:
    fetchpref: true