spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8070/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    gateway:
      enabled: true
  info:
    env:
      enabled: true
      
info:
  app:
    name: "Gateway Server"
    Description: "Bank Gateway Server"
    version: "2023.1"

logging:
  level:
    com:
      springboot:
        BankGatewayServer: DEBUG