spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8070/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 2s

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    gateway:
      enabled: true
  info:
    env:
      enabled: true
      
info:
  app:
    name: "Gateway Server"
    Description: "Bank Gateway Server"
    version: "2023.1"

logging:
  level:
    com:
      springboot:
        BankGatewayServer: DEBUG

resilience4j.circuitbreaker:
  config:
    default:  #Circuit Breaker Name used in Gateway Config Name or Default for all circuit
      slidingWindowSize: 10  # Number of Failure times required change closed to other status
      permittedNumberOfCallsInHalfOpenState: 2  # Number of call need to be send to check service availability
      failureRateThreshold: 50  #(50 Percentage call rate)
      waitDurationInOpenState: 10000  # 10 Seconds